import Foundation

struct Quote {
    let text: String
    let author: String
}

enum Quotes {
    /// Picks today's quote. Two users on the same day see different quotes
    /// because the seed is randomized once per install and persisted to
    /// UserDefaults — so the rotation order is stable for a given user but
    /// shifted from anyone else's.
    @MainActor static func today(now: Date = Date()) -> Quote {
        let cal = Calendar.current
        let dayOfYear = cal.ordinality(of: .day, in: .year, for: now) ?? 1
        let idx = ((dayOfYear - 1) + perUserSeed) % all.count
        return all[idx]
    }

    private static let seedKey = "Flow.quoteSeed.v1"
    @MainActor private static var perUserSeed: Int = {
        let d = UserDefaults.standard
        let stored = d.integer(forKey: seedKey)
        if stored > 0 { return stored }
        let new = Int.random(in: 1...1_000_000)
        d.set(new, forKey: seedKey)
        return new
    }()

    // 365 quotes — founders, operators, stoics, philosophers. Sharp.
    static let all: [Quote] = [
        // — Bezos —
        Quote(text: "Be stubborn on vision, flexible on details.", author: "Bezos"),
        Quote(text: "Your brand is what other people say about you when you're not in the room.", author: "Bezos"),
        Quote(text: "If you double the number of experiments you do per year, you're going to double your inventiveness.", author: "Bezos"),
        Quote(text: "What's dangerous is not to evolve.", author: "Bezos"),
        Quote(text: "Day 2 is stasis, followed by irrelevance, followed by excruciating decline. That's why it's always Day 1.", author: "Bezos"),
        Quote(text: "I knew that if I failed I wouldn't regret it, but I knew the one thing I might regret is not trying.", author: "Bezos"),
        Quote(text: "Cleverness is a gift, kindness is a choice.", author: "Bezos"),
        Quote(text: "If you're not stubborn, you give up too early. If you're not flexible, you pound your head against the wall.", author: "Bezos"),
        Quote(text: "The common question is 'why?' An equally valid question is 'why not?'", author: "Bezos"),
        Quote(text: "Life's too short to hang out with people who aren't resourceful.", author: "Bezos"),
        Quote(text: "Position yourself with something that captures your curiosity, something you're missionary about.", author: "Bezos"),
        Quote(text: "If you're going to do anything new, you have to be willing to be misunderstood.", author: "Bezos"),
        Quote(text: "Invention requires a long-term willingness to be misunderstood.", author: "Bezos"),
        Quote(text: "Failure and invention are inseparable twins.", author: "Bezos"),
        Quote(text: "We are stubborn on vision. We are flexible on details.", author: "Bezos"),
        Quote(text: "Customers are always beautifully, wonderfully dissatisfied.", author: "Bezos"),
        Quote(text: "A company shouldn't get addicted to being shiny, because shiny doesn't last.", author: "Bezos"),
        Quote(text: "Friction makes the magic go away.", author: "Bezos"),
        Quote(text: "I'd much rather have a great life than a long mediocre one.", author: "Bezos"),
        Quote(text: "Good intentions don't work. Mechanisms do.", author: "Bezos"),
        Quote(text: "If you want to be inventive, you have to be willing to fail.", author: "Bezos"),
        Quote(text: "Work hard, have fun, make history.", author: "Bezos"),
        Quote(text: "We humans co-evolve with our tools. We change our tools and then our tools change us.", author: "Bezos"),
        Quote(text: "It's hard to find things that won't sell online.", author: "Bezos"),
        Quote(text: "Long-term thinking levers existing abilities and lets you do new things you couldn't otherwise contemplate.", author: "Bezos"),

        // — Musk —
        Quote(text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Musk"),
        Quote(text: "Failure is an option here. If things are not failing, you are not innovating enough.", author: "Musk"),
        Quote(text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Musk"),
        Quote(text: "Some people don't like change, but you need to embrace it if the alternative is disaster.", author: "Musk"),
        Quote(text: "If you get up in the morning and think the future is going to be better, it is a bright day.", author: "Musk"),
        Quote(text: "Brand is just a perception, and perception will match reality over time.", author: "Musk"),
        Quote(text: "I think life on Earth must be about more than just solving problems.", author: "Musk"),
        Quote(text: "The first step is to establish that something is possible; then probability will occur.", author: "Musk"),
        Quote(text: "You shouldn't do things differently just because they're different. They need to be better.", author: "Musk"),
        Quote(text: "Constantly think about how you could be doing things better.", author: "Musk"),
        Quote(text: "Great companies are built on great products.", author: "Musk"),
        Quote(text: "If you need inspiring words, don't do it.", author: "Musk"),
        Quote(text: "The best part is no part. The best process is no process.", author: "Musk"),
        Quote(text: "I think it's possible for ordinary people to choose to be extraordinary.", author: "Musk"),
        Quote(text: "Don't delude yourself into thinking something's working when it's not.", author: "Musk"),
        Quote(text: "Patience is a virtue, and I'm learning patience. It's a tough lesson.", author: "Musk"),
        Quote(text: "I would rather be optimistic and wrong than pessimistic and right.", author: "Musk"),
        Quote(text: "Starting and growing a business is as much about the innovation, drive, and determination of the people behind it as the product they sell.", author: "Musk"),
        Quote(text: "Talent is extremely important. It's like a sports team — the team that has the best individual players will often win.", author: "Musk"),
        Quote(text: "I don't create companies for the sake of creating companies, but to get things done.", author: "Musk"),
        Quote(text: "The path to the CEO's office should be through engineering and design, not finance.", author: "Musk"),
        Quote(text: "Work like hell. If other people work 40 hours and you put in 100, you'll achieve in four months what takes them a year.", author: "Musk"),
        Quote(text: "If you're trying to create a company, it's like baking a cake. You have all the ingredients in the right proportion.", author: "Musk"),
        Quote(text: "I would like to die on Mars. Just not on impact.", author: "Musk"),
        Quote(text: "It is a mistake to hire huge numbers of people to get a complicated job done. Numbers will never compensate for talent.", author: "Musk"),

        // — Jobs —
        Quote(text: "Your time is limited, so don't waste it living someone else's life.", author: "Jobs"),
        Quote(text: "Stay hungry. Stay foolish.", author: "Jobs"),
        Quote(text: "Innovation distinguishes between a leader and a follower.", author: "Jobs"),
        Quote(text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Jobs"),
        Quote(text: "Quality is more important than quantity. One home run is much better than two doubles.", author: "Jobs"),
        Quote(text: "Get closer than ever to your customers. So close that you tell them what they need before they realize it.", author: "Jobs"),
        Quote(text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Jobs"),
        Quote(text: "Sometimes when you innovate, you make mistakes. Admit them quickly, and get on with improving.", author: "Jobs"),
        Quote(text: "About half of what separates successful entrepreneurs from the non-successful ones is pure perseverance.", author: "Jobs"),
        Quote(text: "Have the courage to follow your heart and intuition.", author: "Jobs"),
        Quote(text: "Things don't have to change the world to be important.", author: "Jobs"),
        Quote(text: "Deciding what not to do is as important as deciding what to do.", author: "Jobs"),
        Quote(text: "I want to put a ding in the universe.", author: "Jobs"),
        Quote(text: "If today were the last day of my life, would I want to do what I am about to do today?", author: "Jobs"),
        Quote(text: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.", author: "Jobs"),
        Quote(text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Jobs"),
        Quote(text: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Jobs"),
        Quote(text: "The only way to do great work is to love what you do.", author: "Jobs"),
        Quote(text: "We hire smart people so they can tell us what to do.", author: "Jobs"),
        Quote(text: "Simplicity is the ultimate sophistication.", author: "Jobs"),
        Quote(text: "Focus and simplicity. Once you get there, you can move mountains.", author: "Jobs"),
        Quote(text: "I'm as proud of many of the things we haven't done as the things we have done.", author: "Jobs"),
        Quote(text: "Real artists ship.", author: "Jobs"),
        Quote(text: "Creativity is just connecting things.", author: "Jobs"),
        Quote(text: "If you are working on something exciting, it will keep you motivated. No plan needed; you'll naturally pursue it.", author: "Jobs"),
        Quote(text: "What is Apple, after all? Apple is about people who think outside the box.", author: "Jobs"),
        Quote(text: "It's more fun to be a pirate than to join the navy.", author: "Jobs"),
        Quote(text: "I'm convinced that the only thing that kept me going was that I loved what I did.", author: "Jobs"),
        Quote(text: "Details matter. It's worth waiting to get it right.", author: "Jobs"),
        Quote(text: "Sometimes life hits you in the head with a brick. Don't lose faith.", author: "Jobs"),

        // — Ford —
        Quote(text: "Whether you think you can, or you think you can't — you're right.", author: "Ford"),
        Quote(text: "Don't find fault, find a remedy.", author: "Ford"),
        Quote(text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Ford"),
        Quote(text: "The only real mistake is the one from which we learn nothing.", author: "Ford"),
        Quote(text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Ford"),
        Quote(text: "If everyone is moving forward together, then success takes care of itself.", author: "Ford"),
        Quote(text: "Quality means doing it right when no one is looking.", author: "Ford"),
        Quote(text: "You can't build a reputation on what you are going to do.", author: "Ford"),
        Quote(text: "Vision without execution is just hallucination.", author: "Ford"),
        Quote(text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Ford"),
        Quote(text: "Thinking is the hardest work there is, which is probably why so few engage in it.", author: "Ford"),
        Quote(text: "Obstacles are those frightful things you see when you take your eyes off your goal.", author: "Ford"),
        Quote(text: "Nothing is particularly hard if you divide it into small jobs.", author: "Ford"),
        Quote(text: "When everything seems to be going against you, remember: the airplane takes off against the wind, not with it.", author: "Ford"),
        Quote(text: "Money is like an arm or leg — use it or lose it.", author: "Ford"),
        Quote(text: "Most people get ahead during the time that others waste.", author: "Ford"),
        Quote(text: "Whether you think you can do a thing or not, you are right.", author: "Ford"),
        Quote(text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Ford"),
        Quote(text: "Enthusiasm is the yeast that makes your hopes shine to the stars.", author: "Ford"),
        Quote(text: "Don't ask if it's possible. Ask if it's worth the cost.", author: "Ford"),

        // — Rockefeller —
        Quote(text: "Don't be afraid to give up the good to go for the great.", author: "Rockefeller"),
        Quote(text: "I do not think there is any other quality so essential to success as the quality of perseverance.", author: "Rockefeller"),
        Quote(text: "I always tried to turn every disaster into an opportunity.", author: "Rockefeller"),
        Quote(text: "The way to make money is to buy when blood is running in the streets.", author: "Rockefeller"),
        Quote(text: "Singleness of purpose is one of the chief essentials for success in life.", author: "Rockefeller"),
        Quote(text: "Good leadership consists of showing average people how to do the work of superior people.", author: "Rockefeller"),
        Quote(text: "I would rather earn 1% off 100 people's efforts than 100% of my own efforts.", author: "Rockefeller"),
        Quote(text: "If you want to succeed, strike out on new paths rather than travel the worn paths of accepted success.", author: "Rockefeller"),
        Quote(text: "The secret of success is to do the common things uncommonly well.", author: "Rockefeller"),
        Quote(text: "The ability to deal with people is as purchasable a commodity as sugar or coffee.", author: "Rockefeller"),
        Quote(text: "Next to doing the right thing, the most important thing is to let people know you are doing the right thing.", author: "Rockefeller"),
        Quote(text: "Every right implies a responsibility; every opportunity, an obligation; every possession, a duty.", author: "Rockefeller"),
        Quote(text: "If you want to be successful, you have to know how to wait.", author: "Rockefeller"),
        Quote(text: "Charity is injurious unless it helps the recipient to become independent of it.", author: "Rockefeller"),
        Quote(text: "I would rather hire a man with enthusiasm than a man who knows everything.", author: "Rockefeller"),

        // — Edison —
        Quote(text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Edison"),
        Quote(text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Edison"),
        Quote(text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Edison"),
        Quote(text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Edison"),
        Quote(text: "The three essentials to achieve anything worthwhile are hard work, stick-to-itiveness, and common sense.", author: "Edison"),
        Quote(text: "If we did all the things we are capable of, we would literally astound ourselves.", author: "Edison"),
        Quote(text: "There is no substitute for hard work.", author: "Edison"),
        Quote(text: "The value of an idea lies in the using of it.", author: "Edison"),
        Quote(text: "Hell, there are no rules here — we're trying to accomplish something.", author: "Edison"),
        Quote(text: "I never did anything by accident; my inventions came by work.", author: "Edison"),
        Quote(text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Edison"),
        Quote(text: "Restlessness is discontent and discontent is the first necessity of progress.", author: "Edison"),
        Quote(text: "I find out what the world needs, then I proceed to invent it.", author: "Edison"),
        Quote(text: "What you are will show in what you do.", author: "Edison"),
        Quote(text: "Show me a thoroughly satisfied man and I will show you a failure.", author: "Edison"),

        // — Einstein —
        Quote(text: "Imagination is more important than knowledge.", author: "Einstein"),
        Quote(text: "Try not to become a man of success, but rather try to become a man of value.", author: "Einstein"),
        Quote(text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Einstein"),
        Quote(text: "Anyone who has never made a mistake has never tried anything new.", author: "Einstein"),
        Quote(text: "The measure of intelligence is the ability to change.", author: "Einstein"),
        Quote(text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Einstein"),
        Quote(text: "In the middle of difficulty lies opportunity.", author: "Einstein"),
        Quote(text: "If you can't explain it simply, you don't understand it well enough.", author: "Einstein"),
        Quote(text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Einstein"),
        Quote(text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Einstein"),
        Quote(text: "Insanity: doing the same thing over and over again and expecting different results.", author: "Einstein"),
        Quote(text: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", author: "Einstein"),
        Quote(text: "Once we accept our limits, we go beyond them.", author: "Einstein"),
        Quote(text: "Weakness of attitude becomes weakness of character.", author: "Einstein"),
        Quote(text: "Only a life lived for others is a life worthwhile.", author: "Einstein"),
        Quote(text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Einstein"),
        Quote(text: "The true sign of intelligence is not knowledge but imagination.", author: "Einstein"),
        Quote(text: "Strive not to be a success, but rather to be of value.", author: "Einstein"),
        Quote(text: "Everything should be made as simple as possible, but not simpler.", author: "Einstein"),
        Quote(text: "I have no special talent. I am only passionately curious.", author: "Einstein"),
        Quote(text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Einstein"),
        Quote(text: "A person who never made a mistake never tried anything new.", author: "Einstein"),
        Quote(text: "Look deep into nature, and then you will understand everything better.", author: "Einstein"),
        Quote(text: "I never think of the future. It comes soon enough.", author: "Einstein"),
        Quote(text: "Education is what remains after one has forgotten what one has learned in school.", author: "Einstein"),

        // — Watts —
        Quote(text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Watts"),
        Quote(text: "Trying to define yourself is like trying to bite your own teeth.", author: "Watts"),
        Quote(text: "This is the real secret of life — to be completely engaged with what you are doing in the here and now.", author: "Watts"),
        Quote(text: "Muddy water is best cleared by leaving it alone.", author: "Watts"),
        Quote(text: "The menu is not the meal.", author: "Watts"),
        Quote(text: "You are an aperture through which the universe is looking at and exploring itself.", author: "Watts"),
        Quote(text: "No valid plans for the future can be made by those who have no capacity for living now.", author: "Watts"),
        Quote(text: "The more a thing tends to be permanent, the more it tends to be lifeless.", author: "Watts"),
        Quote(text: "You are the universe experiencing itself.", author: "Watts"),
        Quote(text: "Tomorrow and plans for tomorrow have no meaning unless you are in contact with the reality of the present.", author: "Watts"),
        Quote(text: "The art of living is neither careless drifting nor fearful clinging to the past.", author: "Watts"),
        Quote(text: "Life is like music for its own sake. We are living in an eternal now.", author: "Watts"),
        Quote(text: "If you cannot trust yourself, you cannot even trust your mistrust of yourself.", author: "Watts"),
        Quote(text: "You don't look out there for God, something in the sky, you look in you.", author: "Watts"),
        Quote(text: "The meaning of life is just to be alive. It is so plain and so obvious and so simple.", author: "Watts"),
        Quote(text: "We do not 'come into' this world; we come out of it, as leaves from a tree.", author: "Watts"),
        Quote(text: "To have faith is to trust yourself to the water.", author: "Watts"),
        Quote(text: "The only Zen you find on the tops of mountains is the Zen you bring up there.", author: "Watts"),
        Quote(text: "The desire for security and the feeling of insecurity are the same thing.", author: "Watts"),
        Quote(text: "A scholar tries to learn something every day; a student of Buddhism tries to unlearn something daily.", author: "Watts"),
        Quote(text: "There will always be suffering. But we must not suffer over the suffering.", author: "Watts"),
        Quote(text: "Words can be sticky things. They get stuck to the things they refer to and confuse the two.", author: "Watts"),
        Quote(text: "What we have forgotten is that thoughts and words are conventions.", author: "Watts"),
        Quote(text: "Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.", author: "Watts"),
        Quote(text: "The only way to make sense of change is to plunge in.", author: "Watts"),

        // — Hormozi —
        Quote(text: "Discipline is just choosing between what you want now and what you want most.", author: "Hormozi"),
        Quote(text: "The amount of pain you can endure determines the level of your success.", author: "Hormozi"),
        Quote(text: "Everything's hard until you make it easy.", author: "Hormozi"),
        Quote(text: "The cost of inaction is greater than the cost of action.", author: "Hormozi"),
        Quote(text: "Boring action beats brilliant inaction every time.", author: "Hormozi"),
        Quote(text: "You can be busy and broke, or productive and prosperous.", author: "Hormozi"),
        Quote(text: "Stop falling in love with your idea. Start falling in love with your audience's problem.", author: "Hormozi"),
        Quote(text: "Most people would rather complain about a problem than spend ten minutes solving it.", author: "Hormozi"),
        Quote(text: "Outwork your self-doubt.", author: "Hormozi"),
        Quote(text: "Success is just a function of how many times you try.", author: "Hormozi"),
        Quote(text: "You have to be willing to do what others won't to get what others can't.", author: "Hormozi"),
        Quote(text: "Your environment determines your output more than your intention does.", author: "Hormozi"),
        Quote(text: "Make the boring move. The boring move is usually the right move.", author: "Hormozi"),
        Quote(text: "Most people quit when the work gets boring, not when it gets hard.", author: "Hormozi"),
        Quote(text: "Confidence is the memory of past success.", author: "Hormozi"),
        Quote(text: "If you want to be successful, find someone who has the results you want, and copy what they do.", author: "Hormozi"),
        Quote(text: "Discipline equals freedom.", author: "Hormozi"),
        Quote(text: "The path is the same: try, fail, learn, repeat.", author: "Hormozi"),
        Quote(text: "Wealth is a side effect of solving problems for others.", author: "Hormozi"),
        Quote(text: "The fastest way to grow is to do the things you don't want to do.", author: "Hormozi"),
        Quote(text: "Volume negates luck.", author: "Hormozi"),
        Quote(text: "Hard work in silence. Let success make the noise.", author: "Hormozi"),
        Quote(text: "If you can't quit, you can't fail.", author: "Hormozi"),
        Quote(text: "You don't need motivation. You need a system.", author: "Hormozi"),
        Quote(text: "Stop trading time for skill. Trade skill for time.", author: "Hormozi"),

        // — Naval —
        Quote(text: "Seek wealth, not money or status.", author: "Naval"),
        Quote(text: "Specific knowledge is found by pursuing your genuine curiosity.", author: "Naval"),
        Quote(text: "Play long-term games with long-term people.", author: "Naval"),
        Quote(text: "Read what you love until you love to read.", author: "Naval"),
        Quote(text: "Earn with your mind, not your time.", author: "Naval"),
        Quote(text: "All the benefits in life come from compound interest.", author: "Naval"),
        Quote(text: "If you can't see yourself working with someone for life, don't work with them for a day.", author: "Naval"),
        Quote(text: "The most important skill for getting rich is becoming a perpetual learner.", author: "Naval"),
        Quote(text: "Free time is the ultimate wealth.", author: "Naval"),
        Quote(text: "Desire is a contract you make with yourself to be unhappy until you get what you want.", author: "Naval"),
        Quote(text: "Anger is a hot coal you hold in your hand while waiting to throw it at somebody else.", author: "Naval"),
        Quote(text: "Embrace accountability and take business risks under your own name.", author: "Naval"),
        Quote(text: "There are no get-rich-quick schemes. That's just someone else getting rich off you.", author: "Naval"),
        Quote(text: "Escape competition through authenticity.", author: "Naval"),
        Quote(text: "Your real résumé is just a catalog of all your suffering.", author: "Naval"),
        Quote(text: "Easy choices, hard life. Hard choices, easy life.", author: "Naval"),
        Quote(text: "Apply specific knowledge with leverage.", author: "Naval"),
        Quote(text: "Without hard work, you'll develop neither judgment nor leverage.", author: "Naval"),
        Quote(text: "A calm mind, a fit body, and a house full of love. These cannot be bought. They must be earned.", author: "Naval"),
        Quote(text: "Doctors won't make you healthy. Nutritionists won't make you slim. Teachers won't make you smart. Save yourself.", author: "Naval"),
        Quote(text: "The most powerful person in the world is the storyteller.", author: "Naval"),
        Quote(text: "Working hard is overrated, working smart is overrated. The most successful people are obsessed.", author: "Naval"),
        Quote(text: "Self-discipline is a form of freedom. Freedom from laziness and lethargy.", author: "Naval"),
        Quote(text: "We waste our time with short-term thinking and busywork.", author: "Naval"),
        Quote(text: "Money buys you freedom in the material world. But it's not going to make you happy.", author: "Naval"),

        // — Munger —
        Quote(text: "The big money is not in the buying and selling, but in the waiting.", author: "Munger"),
        Quote(text: "Spend each day trying to be a little wiser than you were when you woke up.", author: "Munger"),
        Quote(text: "All I want to know is where I'm going to die, so I'll never go there.", author: "Munger"),
        Quote(text: "The first rule of compounding: Never interrupt it unnecessarily.", author: "Munger"),
        Quote(text: "Invert, always invert.", author: "Munger"),
        Quote(text: "Take a simple idea and take it seriously.", author: "Munger"),
        Quote(text: "Long-term advantage comes from trying to be consistently not stupid, instead of trying to be very intelligent.", author: "Munger"),
        Quote(text: "Show me the incentive and I'll show you the outcome.", author: "Munger"),
        Quote(text: "I never allow myself to have an opinion on anything unless I know the other side's argument better than they do.", author: "Munger"),
        Quote(text: "You don't have to be brilliant, only a little bit wiser than the other guys, on average, for a long, long time.", author: "Munger"),
        Quote(text: "The world is full of foolish gamblers; they will not do as well as the patient investor.", author: "Munger"),
        Quote(text: "Acknowledging what you don't know is the dawning of wisdom.", author: "Munger"),
        Quote(text: "Mimicking the herd invites regression to the mean.", author: "Munger"),
        Quote(text: "The best armour of old age is a well-spent life preceding it.", author: "Munger"),
        Quote(text: "Without numerical fluency, you are like a one-legged man in an ass-kicking contest.", author: "Munger"),
        Quote(text: "The way to win is to work, work, work, work and hope to have a few insights.", author: "Munger"),
        Quote(text: "The iron rule of nature is: you get what you reward for.", author: "Munger"),
        Quote(text: "Live within your income and save so that you can invest. Learn what you need to learn.", author: "Munger"),
        Quote(text: "Knowing what you don't know is more useful than being brilliant.", author: "Munger"),
        Quote(text: "Those who keep learning will keep rising in life.", author: "Munger"),

        // — Buffett —
        Quote(text: "Price is what you pay. Value is what you get.", author: "Buffett"),
        Quote(text: "Be fearful when others are greedy, and greedy when others are fearful.", author: "Buffett"),
        Quote(text: "Risk comes from not knowing what you're doing.", author: "Buffett"),
        Quote(text: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", author: "Buffett"),
        Quote(text: "Our favorite holding period is forever.", author: "Buffett"),
        Quote(text: "Never invest in a business you cannot understand.", author: "Buffett"),
        Quote(text: "Rule No. 1: Never lose money. Rule No. 2: Never forget Rule No. 1.", author: "Buffett"),
        Quote(text: "Time is the friend of the wonderful company, the enemy of the mediocre.", author: "Buffett"),
        Quote(text: "Honesty is a very expensive gift. Don't expect it from cheap people.", author: "Buffett"),
        Quote(text: "If you find yourself in a chronically leaking boat, energy devoted to changing vessels beats energy devoted to patching leaks.", author: "Buffett"),
        Quote(text: "Someone is sitting in the shade today because someone planted a tree a long time ago.", author: "Buffett"),
        Quote(text: "The most important investment you can make is in yourself.", author: "Buffett"),
        Quote(text: "Chains of habit are too light to be felt until they are too heavy to be broken.", author: "Buffett"),
        Quote(text: "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble.", author: "Buffett"),
        Quote(text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Buffett"),
        Quote(text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Buffett"),
        Quote(text: "Forecasts may tell you a great deal about the forecaster; they tell you nothing about the future.", author: "Buffett"),
        Quote(text: "I always knew I was going to be rich. I don't think I ever doubted it for a minute.", author: "Buffett"),
        Quote(text: "What we learn from history is that people don't learn from history.", author: "Buffett"),
        Quote(text: "Tell me who your heroes are, and I'll tell you how you'll turn out.", author: "Buffett"),

        // — Thiel —
        Quote(text: "Competition is for losers.", author: "Thiel"),
        Quote(text: "The most contrarian thing of all is not to oppose the crowd but to think for yourself.", author: "Thiel"),
        Quote(text: "If you can identify a delusional popular belief, you can find what lies hidden behind it: the contrarian truth.", author: "Thiel"),
        Quote(text: "The next Bill Gates will not build an operating system. If you copy these guys, you aren't learning from them.", author: "Thiel"),
        Quote(text: "The best entrepreneurs know this: every great business is built around a secret hidden from the outside.", author: "Thiel"),
        Quote(text: "Brilliant thinking is rare, but courage is in even shorter supply than genius.", author: "Thiel"),
        Quote(text: "Why should you expect your own business to succeed without a plan to make it happen?", author: "Thiel"),
        Quote(text: "All happy companies are different: each one earns a monopoly by solving a unique problem.", author: "Thiel"),
        Quote(text: "Doing something different is what's truly good for society and what allows a business to profit.", author: "Thiel"),
        Quote(text: "The most valuable businesses of coming decades will be built by entrepreneurs who empower people.", author: "Thiel"),
        Quote(text: "A startup is the largest endeavor over which you can have definite mastery.", author: "Thiel"),
        Quote(text: "The future will be much better or much worse, but the question is much more open than you think.", author: "Thiel"),
        Quote(text: "Definite optimism works when you build the future you envision.", author: "Thiel"),
        Quote(text: "Begin with the smallest market you can dominate.", author: "Thiel"),
        Quote(text: "Customers won't care about any particular technology unless it solves a particular problem in a superior way.", author: "Thiel"),

        // — Aurelius —
        Quote(text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Aurelius"),
        Quote(text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Aurelius"),
        Quote(text: "Waste no more time arguing what a good man should be. Be one.", author: "Aurelius"),
        Quote(text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Aurelius"),
        Quote(text: "The best revenge is to be unlike him who performed the injury.", author: "Aurelius"),
        Quote(text: "How much trouble he avoids who does not look to see what his neighbor says or does or thinks.", author: "Aurelius"),
        Quote(text: "Confine yourself to the present.", author: "Aurelius"),
        Quote(text: "The happiness of your life depends upon the quality of your thoughts.", author: "Aurelius"),
        Quote(text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Aurelius"),
        Quote(text: "When you arise, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", author: "Aurelius"),
        Quote(text: "You always own the option of having no opinion.", author: "Aurelius"),
        Quote(text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Aurelius"),
        Quote(text: "Reject your sense of injury and the injury itself disappears.", author: "Aurelius"),
        Quote(text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look there.", author: "Aurelius"),
        Quote(text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Aurelius"),
        Quote(text: "Concentrate every minute on doing what's in front of you with precise and genuine seriousness.", author: "Aurelius"),
        Quote(text: "When another blames you or hates you, see deeper into them. Note what kind of people they are.", author: "Aurelius"),
        Quote(text: "Do not act as if you had ten thousand years to live.", author: "Aurelius"),
        Quote(text: "The universe is change; our life is what our thoughts make it.", author: "Aurelius"),
        Quote(text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", author: "Aurelius"),

        // — Seneca —
        Quote(text: "We suffer more in imagination than in reality.", author: "Seneca"),
        Quote(text: "Luck is what happens when preparation meets opportunity.", author: "Seneca"),
        Quote(text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca"),
        Quote(text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca"),
        Quote(text: "Sometimes even to live is an act of courage.", author: "Seneca"),
        Quote(text: "While we wait for life, life passes.", author: "Seneca"),
        Quote(text: "Life is long, if you know how to use it.", author: "Seneca"),
        Quote(text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca"),
        Quote(text: "Wealth is the slave of a wise man. The master of a fool.", author: "Seneca"),
        Quote(text: "All cruelty springs from weakness.", author: "Seneca"),
        Quote(text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca"),
        Quote(text: "Throw me to the wolves and I will return leading the pack.", author: "Seneca"),
        Quote(text: "Every new beginning comes from some other beginning's end.", author: "Seneca"),
        Quote(text: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", author: "Seneca"),
        Quote(text: "If a man knows not which port he sails to, no wind is favorable.", author: "Seneca"),

        // — Epictetus —
        Quote(text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus"),
        Quote(text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus"),
        Quote(text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus"),
        Quote(text: "No man is free who is not master of himself.", author: "Epictetus"),
        Quote(text: "Don't explain your philosophy. Embody it.", author: "Epictetus"),
        Quote(text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus"),
        Quote(text: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", author: "Epictetus"),
        Quote(text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus"),
        Quote(text: "He is a wise man who does not grieve for the things he has not, but rejoices for those he has.", author: "Epictetus"),
        Quote(text: "Caretake this moment. Immerse yourself in its particulars.", author: "Epictetus"),

        // — Roosevelt —
        Quote(text: "It is not the critic who counts; the credit belongs to the man who is actually in the arena.", author: "Roosevelt"),
        Quote(text: "Far better is it to dare mighty things, even though checkered by failure, than to rank with those poor spirits who neither enjoy nor suffer much.", author: "Roosevelt"),
        Quote(text: "Do what you can, with what you have, where you are.", author: "Roosevelt"),
        Quote(text: "Believe you can and you're halfway there.", author: "Roosevelt"),
        Quote(text: "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", author: "Roosevelt"),
        Quote(text: "Comparison is the thief of joy.", author: "Roosevelt"),
        Quote(text: "When you're at the end of your rope, tie a knot and hold on.", author: "Roosevelt"),
        Quote(text: "Keep your eyes on the stars, and your feet on the ground.", author: "Roosevelt"),
        Quote(text: "If you could kick the person responsible for most of your trouble, you wouldn't sit for a month.", author: "Roosevelt"),
        Quote(text: "Old age is like everything else. To make a success of it, you've got to start young.", author: "Roosevelt"),

        // — Carnegie —
        Quote(text: "People who are unable to motivate themselves must be content with mediocrity, no matter how impressive their talents.", author: "Carnegie"),
        Quote(text: "The man who dies thus rich dies disgraced.", author: "Carnegie"),
        Quote(text: "Aim for the highest.", author: "Carnegie"),
        Quote(text: "The first man gets the oyster, the second man gets the shell.", author: "Carnegie"),
        Quote(text: "Take away my people, but leave my factories, and soon grass will grow on the factory floors.", author: "Carnegie"),
        Quote(text: "Do your duty and a little more and the future will take care of itself.", author: "Carnegie"),
        Quote(text: "As I grow older, I pay less attention to what men say. I just watch what they do.", author: "Carnegie"),
        Quote(text: "Concentrate your energies, your thoughts and your capital.", author: "Carnegie"),
        Quote(text: "There is little success where there is little laughter.", author: "Carnegie"),
        Quote(text: "And while the law of competition may be sometimes hard for the individual, it is best for the race.", author: "Carnegie"),

        // — Other heavyweights —
        Quote(text: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Lee"),
        Quote(text: "Be water, my friend.", author: "Lee"),
        Quote(text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Lee"),
        Quote(text: "Absorb what is useful, discard what is useless, add what is essentially your own.", author: "Lee"),
        Quote(text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Lee"),
        Quote(text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Lee"),
        Quote(text: "The successful warrior is the average man, with laser-like focus.", author: "Lee"),
        Quote(text: "To hell with circumstances; I create opportunities.", author: "Lee"),
        Quote(text: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.", author: "Sun Tzu"),
        Quote(text: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu"),
        Quote(text: "Appear weak when you are strong, and strong when you are weak.", author: "Sun Tzu"),
        Quote(text: "The supreme art of war is to subdue the enemy without fighting.", author: "Sun Tzu"),
        Quote(text: "Victorious warriors win first and then go to war.", author: "Sun Tzu"),
        Quote(text: "Opportunities multiply as they are seized.", author: "Sun Tzu"),
        Quote(text: "Move swift as the wind and closely-formed as the wood. Attack like the fire and be still as the mountain.", author: "Sun Tzu"),
        Quote(text: "Learning never exhausts the mind.", author: "Da Vinci"),
        Quote(text: "Simplicity is the ultimate sophistication.", author: "Da Vinci"),
        Quote(text: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them.", author: "Da Vinci"),
        Quote(text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Da Vinci"),
        Quote(text: "Iron rusts from disuse; stagnant water loses its purity. Even so does inaction sap the vigor of the mind.", author: "Da Vinci"),
        Quote(text: "Time stays long enough for those who use it.", author: "Da Vinci"),
        Quote(text: "Obstacles cannot crush me; every obstacle yields to stern resolve.", author: "Da Vinci"),
        Quote(text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius"),
        Quote(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
        Quote(text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius"),
        Quote(text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius"),
        Quote(text: "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.", author: "Confucius"),
        Quote(text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius"),
        Quote(text: "The present is theirs; the future, for which I really worked, is mine.", author: "Tesla"),
        Quote(text: "I don't care that they stole my idea... I care that they don't have any of their own.", author: "Tesla"),
        Quote(text: "If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.", author: "Tesla"),
        Quote(text: "Be alone, that is the secret of invention; be alone, that is when ideas are born.", author: "Tesla"),
        Quote(text: "Our virtues and our failings are inseparable, like force and matter.", author: "Tesla"),
        Quote(text: "Work hard, be kind, and amazing things will happen.", author: "Ellison"),
        Quote(text: "Life's not about how hard you can hit; it's about how hard you can get hit and keep moving forward.", author: "Stallone"),
        Quote(text: "I'd rather regret the things I've done than regret the things I haven't done.", author: "Dietrich"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Disney"),
        Quote(text: "All our dreams can come true, if we have the courage to pursue them.", author: "Disney"),
        Quote(text: "If you can dream it, you can do it.", author: "Disney"),
        Quote(text: "First, think. Second, dream. Third, believe. And finally, dare.", author: "Disney"),
        Quote(text: "Show me a person who has never made a mistake and I'll show you somebody who has never achieved much.", author: "Disney"),
        Quote(text: "Hard work spotlights the character of people.", author: "Lombardi"),
        Quote(text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Lombardi"),
        Quote(text: "Winners never quit, and quitters never win.", author: "Lombardi"),
        Quote(text: "The price of success is hard work, dedication, and the determination that we have applied ourselves.", author: "Lombardi"),
        Quote(text: "If it doesn't challenge you, it won't change you.", author: "Robbins"),
        Quote(text: "The only impossible journey is the one you never begin.", author: "Robbins"),
        Quote(text: "Setting goals is the first step in turning the invisible into the visible.", author: "Robbins"),
        Quote(text: "Your past does not equal your future.", author: "Robbins"),
        Quote(text: "Successful people ask better questions, and as a result, they get better answers.", author: "Robbins"),
        Quote(text: "The path to success is to take massive, determined action.", author: "Robbins"),
        Quote(text: "If you want a better quality of life, change the quality of your questions.", author: "Robbins"),
        Quote(text: "He who has a why to live for can bear almost any how.", author: "Nietzsche"),
        Quote(text: "That which does not kill us makes us stronger.", author: "Nietzsche"),
        Quote(text: "You must have chaos within you to give birth to a dancing star.", author: "Nietzsche"),
        Quote(text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Nietzsche"),
        Quote(text: "Without music, life would be a mistake.", author: "Nietzsche"),
        Quote(text: "Whoever fights monsters should see to it that in the process he does not become a monster.", author: "Nietzsche"),
        Quote(text: "Pain and suffering are always inevitable for a large intelligence and a deep heart.", author: "Dostoevsky"),
        Quote(text: "If you don't make mistakes, you're not working on hard enough problems.", author: "Wozniak"),
        Quote(text: "Wherever smart people work, doors are unlocked.", author: "Wozniak"),
        Quote(text: "Never trust a computer you can't throw out a window.", author: "Wozniak"),
        Quote(text: "Successful investing takes time, discipline and patience.", author: "Lynch"),
        Quote(text: "Know what you own, and know why you own it.", author: "Lynch"),
        Quote(text: "The real key to making money in stocks is not to get scared out of them.", author: "Lynch"),
        Quote(text: "Pain plus reflection equals progress.", author: "Dalio"),
        Quote(text: "He who lives by the crystal ball will eat shattered glass.", author: "Dalio"),
        Quote(text: "Truth — more precisely, an accurate understanding of reality — is the essential foundation for any good outcome.", author: "Dalio"),
        Quote(text: "Being radically truthful and radically transparent with each other accelerates our learning.", author: "Dalio"),
        Quote(text: "Don't worry about looking good; worry about achieving your goals.", author: "Dalio"),
        Quote(text: "Successful entrepreneurs are skilled at gauging risks.", author: "Cuban"),
        Quote(text: "It doesn't matter how many times you fail. You only have to be right once.", author: "Cuban"),
        Quote(text: "Work like there is someone working 24 hours a day to take it all away from you.", author: "Cuban"),
        Quote(text: "Sweat equity is the most valuable equity there is.", author: "Cuban"),
        Quote(text: "Every no gets me closer to a yes.", author: "Cuban"),
        Quote(text: "It is not the strongest of the species that survives, but the most adaptable.", author: "Darwin"),
        Quote(text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Darwin"),
        Quote(text: "Ignorance more frequently begets confidence than does knowledge.", author: "Darwin"),
        Quote(text: "Build something 100 people love, not something 1 million people kind of like.", author: "Graham"),
        Quote(text: "The way to get startup ideas is not to try to think of startup ideas. It's to look for problems.", author: "Graham"),
        Quote(text: "Live in the future, then build what's missing.", author: "Graham"),
        Quote(text: "Beware of advice from people who haven't built anything.", author: "Graham"),
        Quote(text: "Successful people do whatever needs to be done.", author: "Graham"),
        Quote(text: "Find something you want so much that you're willing to chase it for a decade.", author: "Altman"),
        Quote(text: "The right amount of obsession is the kind that makes you uncomfortable.", author: "Altman"),
        Quote(text: "Most things are uncorrelated. Compounding edges is rare.", author: "Altman"),
        Quote(text: "Move fast. Speed is one of your main advantages over large competitors.", author: "Altman"),
        Quote(text: "You have to give yourself permission to think big.", author: "Altman"),
        Quote(text: "Doing things that don't scale is a phase, not a destiny.", author: "Altman"),
        Quote(text: "Bad excuses are worse than no excuses.", author: "Hoffman"),
        Quote(text: "If you're not embarrassed by the first version of your product, you've launched too late.", author: "Hoffman"),
        Quote(text: "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down.", author: "Hoffman"),
        Quote(text: "No matter how brilliant your mind or strategy, if you're playing a solo game, you'll always lose.", author: "Hoffman"),
        Quote(text: "The fastest way to change yourself is to hang out with people who are already the way you want to be.", author: "Hoffman"),
        Quote(text: "What gets measured gets managed.", author: "Drucker"),
        Quote(text: "The best way to predict the future is to create it.", author: "Drucker"),
        Quote(text: "Doing the right thing is more important than doing the thing right.", author: "Drucker"),
        Quote(text: "Plans are only good intentions unless they immediately degenerate into hard work.", author: "Drucker"),
        Quote(text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Drucker"),
        Quote(text: "Culture eats strategy for breakfast.", author: "Drucker"),
        Quote(text: "The most important thing in communication is hearing what isn't said.", author: "Drucker"),
        Quote(text: "Do what you have to do until you can do what you want to do.", author: "Winfrey"),
        Quote(text: "Doing your best at this moment puts you in the best place for the next moment.", author: "Winfrey"),
        Quote(text: "Turn your wounds into wisdom.", author: "Winfrey"),
        Quote(text: "Don't worry about being successful but work toward being significant.", author: "Winfrey"),
        Quote(text: "Eighty percent of success is showing up.", author: "Allen"),
        Quote(text: "Life is what happens to you while you're busy making other plans.", author: "Lennon"),
        Quote(text: "I dream of painting and then I paint my dream.", author: "Van Gogh"),
        Quote(text: "Great things are not done by impulse, but by a series of small things brought together.", author: "Van Gogh"),
        Quote(text: "Don't tell me the moon is shining; show me the glint of light on broken glass.", author: "Chekhov"),
        Quote(text: "Action is the foundational key to all success.", author: "Picasso"),
        Quote(text: "Every act of creation is first an act of destruction.", author: "Picasso"),
        Quote(text: "Inspiration exists, but it has to find you working.", author: "Picasso"),
        Quote(text: "The chief enemy of creativity is good sense.", author: "Picasso"),
        Quote(text: "Discipline is the bridge between goals and accomplishment.", author: "Rohn"),
        Quote(text: "Either you run the day or the day runs you.", author: "Rohn"),
        Quote(text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Rohn"),
        Quote(text: "You are the average of the five people you spend the most time with.", author: "Rohn"),
        Quote(text: "Don't wish it were easier; wish you were better.", author: "Rohn"),
        Quote(text: "Time is more valuable than money. You can get more money, but you cannot get more time.", author: "Rohn"),
        Quote(text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Rohn"),
        Quote(text: "Take care of your body. It's the only place you have to live.", author: "Rohn"),
        Quote(text: "Don't let what you cannot do interfere with what you can do.", author: "Wooden"),
        Quote(text: "It's the little details that are vital. Little things make big things happen.", author: "Wooden"),
        Quote(text: "Things turn out best for the people who make the best of the way things turn out.", author: "Wooden"),
        Quote(text: "Failure isn't fatal, but failure to change might be.", author: "Wooden"),
        Quote(text: "Be more concerned with your character than your reputation.", author: "Wooden"),
        Quote(text: "If you don't have time to do it right, when will you have time to do it over?", author: "Wooden"),
        Quote(text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Jordan"),
        Quote(text: "I've missed more than 9000 shots in my career. I've failed over and over. That is why I succeed.", author: "Jordan"),
        Quote(text: "Talent wins games, but teamwork and intelligence win championships.", author: "Jordan"),
        Quote(text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Jordan"),
        Quote(text: "Obstacles don't have to stop you. If you run into a wall, don't turn around. Figure out how to climb it.", author: "Jordan"),
        Quote(text: "Just keep swimming.", author: "Anonymous"),
    ]
}
